"""Draft command/skill generator.

When a lesson matures, generates a draft slash command that encodes
the fix pattern, following the kernel's command markdown template.
"""

import re
from typing import List


def suggest_command_name(issue: str, tags: List[str]) -> str:
    """Derive a kebab-case command name from issue description and tags.

    Args:
        issue: The issue description.
        tags: Categorization tags.

    Returns:
        A kebab-case string suitable for a command filename.
    """
    # Start with first tag if available, otherwise use issue
    base = tags[0] if tags else ""

    # Extract key words from issue
    words = re.findall(r'[a-zA-Z]+', issue.lower())

    # Remove common stop words
    stop_words = {'the', 'a', 'an', 'is', 'was', 'were', 'in', 'on', 'at',
                  'to', 'for', 'of', 'with', 'by', 'from', 'via', 'not'}
    key_words = [w for w in words if w not in stop_words]

    # Build name: "check-" prefix + key words (max 4)
    name_parts = ["check"]
    if base and base not in key_words:
        name_parts.append(base)
    name_parts.extend(key_words[:3])

    return "-".join(name_parts)


def generate_draft(
    pattern_key: str,
    issue: str,
    fix: str,
    tags: List[str],
) -> dict:
    """Generate a draft slash command from a mature lesson.

    Args:
        pattern_key: The fingerprint of the source lesson.
        issue: The issue description.
        fix: The fix description/pattern.
        tags: Categorization tags.

    Returns:
        Dict with command_name, command_path, content, source_pattern.
    """
    command_name = suggest_command_name(issue, tags)
    command_path = f".claude/commands/kernel/{command_name}.md"

    content = f"""# /kernel/{command_name}

Check for and prevent: {issue}

## Instructions

1. **Identify the pattern:**
   - Look for signs of: {issue}
   - Common trigger: recurring issue (pattern key: `{pattern_key}`)

2. **Apply the fix:**
   {fix}

3. **Verify the fix:**
   - Confirm the issue is resolved
   - Check that no regression was introduced

4. **Report:**
   ```
   CHECK COMPLETE: {command_name}

   Pattern: {pattern_key}
   Issue found: [yes/no]
   Fix applied: [yes/no]
   ```

## When to Invoke

- When you encounter: {issue}
- Auto-generated from lesson pattern `{pattern_key}`
- Tags: {', '.join(tags) if tags else 'none'}

## Source

Auto-extracted from mature lesson (pattern key: `{pattern_key}`).
This command was generated by the skill extraction system.
"""

    return {
        "command_name": command_name,
        "command_path": command_path,
        "content": content,
        "source_pattern": pattern_key,
    }
